name: Build & Upload to Firebase

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17


      - name: Setup Android SDK
        uses: android-actions/setup-android@v3


      - name: Install Firebase CLI
        run: npm install -g firebase-tools


      - name: Install jq
        run: sudo apt-get install jq


      ###########################################
      # Get latest version from Firebase
      ###########################################

      - name: Get latest Firebase version
        id: firebase_version
        run: |

          latest_release=$(firebase appdistribution:releases:list \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --limit 1 \
            --output json \
            --token "${{ secrets.FIREBASE_TOKEN }}")

          echo "Latest release:"
          echo $latest_release

          versionName=$(echo $latest_release | jq -r '.[0].displayVersion // "1.0.0"')
          versionCode=$(echo $latest_release | jq -r '.[0].buildVersion // "1"')

          echo "Current versionName=$versionName"
          echo "Current versionCode=$versionCode"

          IFS='.' read -r major minor patch <<< "$versionName"

          patch=$((patch+1))

          newVersionName="$major.$minor.$patch"

          newVersionCode=$((versionCode+1))

          echo "NEW_VERSION_NAME=$newVersionName" >> $GITHUB_ENV
          echo "NEW_VERSION_CODE=$newVersionCode" >> $GITHUB_ENV


      ###########################################
      # Build APK
      ###########################################

      - name: Build Release APK
        run: |

          ./gradlew clean assembleRelease \
          -PVERSION_NAME=$NEW_VERSION_NAME \
          -PVERSION_CODE=$NEW_VERSION_CODE


      ###########################################
      # Upload to Firebase
      ###########################################

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:

          appId: ${{ secrets.FIREBASE_APP_ID }}

          token: ${{ secrets.FIREBASE_TOKEN }}

          groups: qa-team

          file: app/build/outputs/apk/release/app-release.apk

          releaseNotesFile: app/build/release-notes.txt