name: Build Signed APK & Upload to Firebase

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: "Environment"
        required: false
        default: ""

      CORE_VERSION:
        description: "Core SDK version"
        required: false
        default: ""

      CAMERA_VERSION:
        description: "Camera SDK version"
        required: false
        default: ""

      MEDIA_VERSION:
        description: "Media SDK version"
        required: false
        default: ""

      IMAGE_VERSION:
        description: "Image SDK version"
        required: false
        default: ""

      VIDEO_VERSION:
        description: "Video SDK version"
        required: false
        default: ""
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17


      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install jq
        run: sudo apt-get install jq


      # create keystore file in runner
      - name: Decode keystore
        run: |

          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

          echo "KEYSTORE_PATH=$PWD/keystore.jks" >> $GITHUB_ENV


      # auto version increment from firebase latest release
      - name: Generate version
        run: |

          VERSION_CODE=${{ github.run_number }}

          VERSION_NAME="1.0.${{ github.run_number }}"

          echo "NEW_VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

          echo "NEW_VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

          echo "Version:"
          echo "$VERSION_NAME ($VERSION_CODE)"
        

      # update version.properties
      - name: Update SDK versions if provided
        run: |

          FILE=app/src/main/assets/version.properties

          echo "Before update:"
          cat $FILE

          update_value () {
            KEY=$1
            VALUE=$2

            if [ ! -z "$VALUE" ]; then
              sed -i "s/^$KEY=.*/$KEY=$VALUE/" $FILE
            fi
          }

          update_value "Env" "${{ github.event.inputs.ENV }}"
          update_value "core" "${{ github.event.inputs.CORE_VERSION }}"
          update_value "camera" "${{ github.event.inputs.CAMERA_VERSION }}"
          update_value "media" "${{ github.event.inputs.MEDIA_VERSION }}"
          update_value "image" "${{ github.event.inputs.IMAGE_VERSION }}"
          update_value "video" "${{ github.event.inputs.VIDEO_VERSION }}"

          echo "After update:"
          cat $FILE

#      # Unit test cases
#      - name: Run Unit Tests
#        run: |
#
#          echo "Running unit tests..."
#
#          ./gradlew testDebugUnitTest
#
#          echo ""
#          echo "Test summary:"
#
#          TOTAL=$(grep -r "testsuite" app/build/test-results/testDebugUnitTest/*.xml | grep -o 'tests="[0-9]*"' | grep -o '[0-9]*' | awk '{sum+=$1} END {print sum}')
#
#          FAILURES=$(grep -r "testsuite" app/build/test-results/testDebugUnitTest/*.xml | grep -o 'failures="[0-9]*"' | grep -o '[0-9]*' | awk '{sum+=$1} END {print sum}')
#
#          PASSED=$((TOTAL-FAILURES))
#
#          echo "Total tests: $TOTAL"
#          echo "Passed: $PASSED"
#          echo "Failed: $FAILURES"
#
#          if [ "$FAILURES" != "0" ]; then
#            echo "Unit tests failed ❌"
#            exit 1
#          fi
#
#          echo "All tests passed ✅"
#
#      # UI test cases
#      - name: Run UI tests
#
#        continue-on-error: true
#
#        uses: reactivecircus/android-emulator-runner@v2
#
#        with:
#
#          api-level: 28
#
#          arch: x86
#
#          target: default
#
#          profile: Nexus 6
#
#          emulator-options: -no-window -noaudio -gpu swiftshader_indirect -no-boot-anim -no-snapshot
#
#          emulator-boot-timeout: 600
#
#          script: |
#
#            adb wait-for-device
#
#            sleep 20
#
#            ./gradlew connectedDebugAndroidTest
#
#      - name: Print UI test summary
#
#        if: always()
#
#        run: |
#
#          echo "Checking UI test results..."
#
#          if ls app/build/outputs/androidTest-results/connected/*.xml 1> /dev/null 2>&1; then
#
#            TOTAL=$(grep -r "testsuite" app/build/outputs/androidTest-results/connected/*.xml | grep -o 'tests="[0-9]*"' | grep -o '[0-9]*' | awk '{sum+=$1} END {print sum}')
#
#            FAILURES=$(grep -r "testsuite" app/build/outputs/androidTest-results/connected/*.xml | grep -o 'failures="[0-9]*"' | grep -o '[0-9]*' | awk '{sum+=$1} END {print sum}')
#
#            PASSED=$((TOTAL-FAILURES))
#
#            echo "UI Tests Total: $TOTAL"
#            echo "UI Tests Passed: $PASSED"
#            echo "UI Tests Failed: $FAILURES"
#
#          else
#
#            echo "No UI test report found"
#
#          fi

      # build signed release apk
      - name: Build signed APK
        env:

          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

          KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}

        run: |

          ./gradlew clean assembleRelease \
          -PVERSION_NAME=$NEW_VERSION_NAME \
          -PVERSION_CODE=$NEW_VERSION_CODE


      # verify apk exists
      - name: Verify APK
        run: |

          echo "APK files:"
          find app/build -name "*.apk"


      # upload to firebase
      - name: Upload to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:

          appId: ${{ secrets.FIREBASE_APP_ID }}

          token: ${{ secrets.FIREBASE_TOKEN }}

          groups: testers

          file: app/build/outputs/apk/release/app-release.apk

          releaseNotesFile: app/build/release-notes.txt


      - name: Slack Notification

        if: always()

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ENVIRONMENT: ${{ github.event.inputs.ENV }}
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_ID: ${{ github.sha }}
          ACTOR: ${{ github.actor }}

        run: |

          if [ "${{ job.status }}" = "success" ]; then
            MESSAGE="✅ Build Successful"
          else
            MESSAGE="❌ Build Failed"
          fi

          curl -X POST "$SLACK_WEBHOOK_URL" \
          -H "Content-Type: application/json" \
          -d "{
                \"text\": \"📱 APK Build Update\n\n$MESSAGE\n\nApp Version: $NEW_VERSION_NAME ($NEW_VERSION_CODE)\nEnvironment: $ENVIRONMENT\nBranch: $BRANCH_NAME\nCommit: $COMMIT_ID\nTriggered by: $ACTOR\nFirebase: uploaded successfully 🚀\"
              }"

      - name: Create Jira Ticket

        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}

        run: |

          echo "Using URL: $JIRA_BASE_URL"

          ISSUE_RESPONSE=$(curl -u $JIRA_EMAIL:$JIRA_API_TOKEN \
            -X POST \
            -H "Content-Type: application/json" \
            --data "{
              \"fields\": {
                \"project\": {
                  \"key\": \"$JIRA_PROJECT_KEY\"
                },
                \"summary\": \"Regression Testing - Build $NEW_VERSION_NAME ($NEW_VERSION_CODE)\",
                \"description\": \"Build available on Firebase.\",
                \"issuetype\": {
                  \"name\": \"Story\"
                },
                \"labels\": [\"Regression\"]
              }
            }" \
            $JIRA_BASE_URL/rest/api/3/issue)

          echo "Response:"
          echo $ISSUE_RESPONSE
