name: Build Signed APK & Upload to Firebase

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17


      - name: Setup Android SDK
        uses: android-actions/setup-android@v3


      - name: Install Firebase CLI
        run : | 
          npm install -g firebase-tools@latest
          firebase --version 


      - name: Install jq
        run: sudo apt-get install jq


      # create keystore file in runner
      - name: Decode keystore
        run: |

          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

          echo "KEYSTORE_PATH=$PWD/keystore.jks" >> $GITHUB_ENV


      # auto version increment from firebase latest release
      - name: Get latest Firebase version
        run: |

          set +e

          latest_release=$(npx firebase-tools appdistribution:releases:list \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --limit 1 \
            --output json \
            --token "${{ secrets.FIREBASE_TOKEN }}")

          exit_code=$?

          set -e

          echo "Firebase response:"
          echo "$latest_release"

          if [ $exit_code -ne 0 ] || [ -z "$latest_release" ] || [ "$latest_release" = "[]" ]; then

            echo "No previous release found"

            versionName="1.0.0"
            versionCode=1

          else

            versionName=$(echo "$latest_release" | jq -r '.[0].displayVersion // "1.0.0"')
            versionCode=$(echo "$latest_release" | jq -r '.[0].buildVersion // "1"')

          fi

          IFS='.' read -r major minor patch <<< "$versionName"

          major=${major:-1}
          minor=${minor:-0}
          patch=${patch:-0}

          patch=$((patch+1))

          newVersionName="$major.$minor.$patch"
          newVersionCode=$((versionCode+1))

          echo "NEW_VERSION_NAME=$newVersionName" >> $GITHUB_ENV
          echo "NEW_VERSION_CODE=$newVersionCode" >> $GITHUB_ENV


      # build signed release apk
      - name: Build signed APK
        env:

          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

          KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}

        run: |

          ./gradlew clean assembleRelease \
          -PVERSION_NAME=$NEW_VERSION_NAME \
          -PVERSION_CODE=$NEW_VERSION_CODE


      # verify apk exists
      - name: Verify APK
        run: |

          echo "APK files:"
          find app/build -name "*.apk"


      # upload to firebase
      - name: Upload to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:

          appId: ${{ secrets.FIREBASE_APP_ID }}

          token: ${{ secrets.FIREBASE_TOKEN }}

          groups: testers

          file: app/build/outputs/apk/release/app-release.apk

          releaseNotesFile: app/build/release-notes.txt