name: GitHub Actions Demo
run-name: Github is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: 2048game
          path: app/build/outputs/apk/debug/app-debug.apk

#            # Create APK Release
#      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
#        run: ./gradlew assemble
#
#            # Create Bundle AAB Release
#            # Noted for main module build [main_project_module]:bundleRelease
#      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
#        run: ./gradlew ${{ env.main_project_module }}:bundleRelease
#
#            # Upload Artifact Build
#            # Noted For Output [main_project_module]/build/outputs/apk/debug/
#      - name: Upload APK Debug - ${{ env.repository_name }}
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
#          path: ${{ env.main_project_module }}/build/outputs/apk/debug/
#
#            # Noted For Output [main_project_module]/build/outputs/apk/release/
#      - name: Upload APK Release - ${{ env.repository_name }}
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
#          path: ${{ env.main_project_module }}/build/outputs/apk/release/
#
#            # Noted For Output [main_project_module]/build/outputs/bundle/release/
#      - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
#          path: ${{ env.main_project_module }}/build/outputs/bundle/release/